/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PassTokenRouteImport } from './routes/pass.$token'
import { Route as LoginScannerRouteImport } from './routes/login.scanner'
import { Route as LoginPosRouteImport } from './routes/login.pos'
import { Route as LoginDashboardRouteImport } from './routes/login.dashboard'
import { Route as LoginAdminRouteImport } from './routes/login.admin'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassTokenRoute = PassTokenRouteImport.update({
  id: '/pass/$token',
  path: '/pass/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginScannerRoute = LoginScannerRouteImport.update({
  id: '/login/scanner',
  path: '/login/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPosRoute = LoginPosRouteImport.update({
  id: '/login/pos',
  path: '/login/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginDashboardRoute = LoginDashboardRouteImport.update({
  id: '/login/dashboard',
  path: '/login/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/login/admin',
  path: '/login/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/dashboard': typeof LoginDashboardRoute
  '/login/pos': typeof LoginPosRoute
  '/login/scanner': typeof LoginScannerRoute
  '/pass/$token': typeof PassTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/dashboard': typeof LoginDashboardRoute
  '/login/pos': typeof LoginPosRoute
  '/login/scanner': typeof LoginScannerRoute
  '/pass/$token': typeof PassTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/dashboard': typeof LoginDashboardRoute
  '/login/pos': typeof LoginPosRoute
  '/login/scanner': typeof LoginScannerRoute
  '/pass/$token': typeof PassTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/login/admin'
    | '/login/dashboard'
    | '/login/pos'
    | '/login/scanner'
    | '/pass/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/login/admin'
    | '/login/dashboard'
    | '/login/pos'
    | '/login/scanner'
    | '/pass/$token'
  id:
    | '__root__'
    | '/'
    | '/register'
    | '/login/admin'
    | '/login/dashboard'
    | '/login/pos'
    | '/login/scanner'
    | '/pass/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterRoute: typeof RegisterRoute
  LoginAdminRoute: typeof LoginAdminRoute
  LoginDashboardRoute: typeof LoginDashboardRoute
  LoginPosRoute: typeof LoginPosRoute
  LoginScannerRoute: typeof LoginScannerRoute
  PassTokenRoute: typeof PassTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pass/$token': {
      id: '/pass/$token'
      path: '/pass/$token'
      fullPath: '/pass/$token'
      preLoaderRoute: typeof PassTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/scanner': {
      id: '/login/scanner'
      path: '/login/scanner'
      fullPath: '/login/scanner'
      preLoaderRoute: typeof LoginScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/pos': {
      id: '/login/pos'
      path: '/login/pos'
      fullPath: '/login/pos'
      preLoaderRoute: typeof LoginPosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/dashboard': {
      id: '/login/dashboard'
      path: '/login/dashboard'
      fullPath: '/login/dashboard'
      preLoaderRoute: typeof LoginDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/login/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterRoute: RegisterRoute,
  LoginAdminRoute: LoginAdminRoute,
  LoginDashboardRoute: LoginDashboardRoute,
  LoginPosRoute: LoginPosRoute,
  LoginScannerRoute: LoginScannerRoute,
  PassTokenRoute: PassTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
