/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PosRouteImport } from './routes/pos'
import { Route as MyPassesRouteImport } from './routes/my-passes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PassTokenRouteImport } from './routes/pass.$token'
import { Route as LoginScannerRouteImport } from './routes/login.scanner'
import { Route as LoginPosRouteImport } from './routes/login.pos'
import { Route as LoginDashboardRouteImport } from './routes/login.dashboard'
import { Route as LoginAdminRouteImport } from './routes/login.admin'

const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPassesRoute = MyPassesRouteImport.update({
  id: '/my-passes',
  path: '/my-passes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassTokenRoute = PassTokenRouteImport.update({
  id: '/pass/$token',
  path: '/pass/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginScannerRoute = LoginScannerRouteImport.update({
  id: '/login/scanner',
  path: '/login/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPosRoute = LoginPosRouteImport.update({
  id: '/login/pos',
  path: '/login/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginDashboardRoute = LoginDashboardRouteImport.update({
  id: '/login/dashboard',
  path: '/login/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/login/admin',
  path: '/login/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/my-passes': typeof MyPassesRoute
  '/pos': typeof PosRoute
  '/register': typeof RegisterRoute
  '/scanner': typeof ScannerRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/dashboard': typeof LoginDashboardRoute
  '/login/pos': typeof LoginPosRoute
  '/login/scanner': typeof LoginScannerRoute
  '/pass/$token': typeof PassTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/my-passes': typeof MyPassesRoute
  '/pos': typeof PosRoute
  '/register': typeof RegisterRoute
  '/scanner': typeof ScannerRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/dashboard': typeof LoginDashboardRoute
  '/login/pos': typeof LoginPosRoute
  '/login/scanner': typeof LoginScannerRoute
  '/pass/$token': typeof PassTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/my-passes': typeof MyPassesRoute
  '/pos': typeof PosRoute
  '/register': typeof RegisterRoute
  '/scanner': typeof ScannerRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/dashboard': typeof LoginDashboardRoute
  '/login/pos': typeof LoginPosRoute
  '/login/scanner': typeof LoginScannerRoute
  '/pass/$token': typeof PassTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/my-passes'
    | '/pos'
    | '/register'
    | '/scanner'
    | '/login/admin'
    | '/login/dashboard'
    | '/login/pos'
    | '/login/scanner'
    | '/pass/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/my-passes'
    | '/pos'
    | '/register'
    | '/scanner'
    | '/login/admin'
    | '/login/dashboard'
    | '/login/pos'
    | '/login/scanner'
    | '/pass/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/my-passes'
    | '/pos'
    | '/register'
    | '/scanner'
    | '/login/admin'
    | '/login/dashboard'
    | '/login/pos'
    | '/login/scanner'
    | '/pass/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  MyPassesRoute: typeof MyPassesRoute
  PosRoute: typeof PosRoute
  RegisterRoute: typeof RegisterRoute
  ScannerRoute: typeof ScannerRoute
  LoginAdminRoute: typeof LoginAdminRoute
  LoginDashboardRoute: typeof LoginDashboardRoute
  LoginPosRoute: typeof LoginPosRoute
  LoginScannerRoute: typeof LoginScannerRoute
  PassTokenRoute: typeof PassTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-passes': {
      id: '/my-passes'
      path: '/my-passes'
      fullPath: '/my-passes'
      preLoaderRoute: typeof MyPassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pass/$token': {
      id: '/pass/$token'
      path: '/pass/$token'
      fullPath: '/pass/$token'
      preLoaderRoute: typeof PassTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/scanner': {
      id: '/login/scanner'
      path: '/login/scanner'
      fullPath: '/login/scanner'
      preLoaderRoute: typeof LoginScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/pos': {
      id: '/login/pos'
      path: '/login/pos'
      fullPath: '/login/pos'
      preLoaderRoute: typeof LoginPosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/dashboard': {
      id: '/login/dashboard'
      path: '/login/dashboard'
      fullPath: '/login/dashboard'
      preLoaderRoute: typeof LoginDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/login/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  MyPassesRoute: MyPassesRoute,
  PosRoute: PosRoute,
  RegisterRoute: RegisterRoute,
  ScannerRoute: ScannerRoute,
  LoginAdminRoute: LoginAdminRoute,
  LoginDashboardRoute: LoginDashboardRoute,
  LoginPosRoute: LoginPosRoute,
  LoginScannerRoute: LoginScannerRoute,
  PassTokenRoute: PassTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
